export const IPC_CHANNELS = {
  profilesGetAll: 'profiles:get-all',
  profilesGet: 'profiles:get',
  profilesCreate: 'profiles:create',
  profilesUpdate: 'profiles:update',
  profilesDelete: 'profiles:delete',
  dialogSelectKeyfile: 'dialog:select-keyfile',
  sshConnect: 'ssh:connect',
  sshDisconnect: 'ssh:disconnect',
  sshConnectionClosed: 'ssh:connection-closed',
  sftpListDirectory: 'sftp:list-directory',
  sftpDownload: 'sftp:download',
  sftpSearchInDirectory: 'sftp:search-in-directory',
  bookmarksAdd: 'bookmarks:add',
  bookmarksRemove: 'bookmarks:remove',
  logsGetFileInfo: 'logs:get-file-info',
  logsReadLines: 'logs:read-lines',
  logsStartTail: 'logs:start-tail',
  logsStopTail: 'logs:stop-tail',
  logsSearchByDateRange: 'logs:search-by-date-range',
  logsGrep: 'logs:grep',
  logsData: 'logs:data',
  terminalStart: 'terminal:start',
  terminalWrite: 'terminal:write',
  terminalResize: 'terminal:resize',
  terminalStop: 'terminal:stop',
  terminalData: 'terminal:data',
} as const;

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];
